BLOCKING={'shelf','table','plant','TV','tree','piano','barrel','stove','panel','suitcase','crate','snowman','skirack','fireplace',
 'wheel','telescope','slot','anchor','sarcophagus','palm','painting','armour','dinosaur','gem','geode','statue','tent','ferris','mirror','pole','candy','target','fountain','desk','cart','washer','boiler','lift'}
MAPS=[
dict(id='c4',num='04',title='The Midnight Express',difficulty='Easy',
 rooms=["EEDDD","EEDDD","SSSLL","SSLLL","BBBBL"],
 roomNames=dict(E='Engine',D='Dining car',S='Sleeper',L='Lounge car',B='Luggage van'),
 floors=dict(E='metal',D='carpet',S='wood',L='marble',B='metal'),
 objects=[('panel',[(0,0)]),('barrel',[(1,1)]),('table',[(0,3)]),('chair',[(0,2)]),('chair',[(0,4)]),('table',[(1,3)]),
  ('bed',[(2,0),(2,1)]),('piano',[(2,4)]),('sofa',[(3,3),(3,4)]),('suitcase',[(4,0)]),('crate',[(4,2)])],
 names=['Alma','Basil','Cora','Declan','Esme']),
dict(id='c5',num='05',title='Frostpeak Lodge',difficulty='Medium',
 rooms=["DDDKKK","DBBKKH","DBBLLH","SSLLLH","SSLLTT","SSSTTT"],
 roomNames=dict(D='Deck',K='Kitchen',B='Bunk room',H='Hot tub',L='Lounge',S='Ski room',T='Sauna'),
 floors=dict(D='snow',K='tile',B='wood',H='water',L='carpet',S='stone',T='sand'),
 objects=[('snowman',[(0,0)]),('stove',[(0,4)]),('chair',[(0,3)]),('table',[(1,4)]),('bed',[(1,1),(2,1)]),('chair',[(1,2)]),
  ('fireplace',[(3,3)]),('carpet',[(4,2),(4,3)]),('sofa',[(2,3),(2,4)]),('skirack',[(5,0)]),('bench',[(3,0),(4,0)]),('bench',[(5,4),(5,5)]),('plant',[(1,0)])],
 names=['Axel','Brigid','Caspar','Delphine','Ezra','Freya']),
dict(id='c6',num='06',title='The Grand Aurora',difficulty='Medium',
 rooms=["BBBCCCC","BBPPCCC","DPPPPCS","DDPPKKS","DDWWKKS","LLWWKSS","LLLWWSS"],
 roomNames=dict(B='Bridge',C='Casino',P='Pool',S='Spa',D='Dining',K='Galley',W='Ballroom',L='Lifeboat deck'),
 floors=dict(B='metal',C='carpet',P='water',S='marble',D='wood',K='tile',W='wood',L='pavement'),
 objects=[('wheel',[(0,1)]),('telescope',[(1,0)]),('slot',[(0,4)]),('slot',[(0,6)]),('table',[(1,5),(1,6)]),('chair',[(0,5)]),
  ('float',[(2,3)]),('table',[(3,0)]),('chair',[(4,0)]),('stove',[(4,5)]),('crate',[(3,4)]),('plant',[(2,6)]),('bathtub',[(6,5),(6,6)]),
  ('piano',[(4,3)]),('anchor',[(5,0)]),('lifeboat',[(6,0),(6,1)])],
 names=['Adele','Bernard','Clio','Dorian','Elsa','Fitz','Greer']),
dict(id='c7',num='07',title='Museum After Dark',difficulty='Hard',
 rooms=["EEEEGGGG","EEEEGGGG","AAHHHHVV","AAHHHHVV","AAHHHHMM","SSSHHMMM","SSSCCCMM","SSSCCCCC"],
 roomNames=dict(E='Egypt wing',G='Gallery',A='Armoury',H='Great hall',V='Vault',M='Mineral room',S='Sculpture court',C='Cafe'),
 floors=dict(E='sand',G='wood',A='stone',H='marble',V='metal',M='stone',S='grass',C='tile'),
 objects=[('sarcophagus',[(0,1),(0,2)]),('palm',[(1,3)]),('painting',[(0,5)]),('painting',[(1,7)]),('bench',[(1,4),(1,5)]),
  ('armour',[(2,0)]),('armour',[(4,1)]),('dinosaur',[(3,3),(3,4),(4,3),(4,4)]),('carpet',[(2,2),(2,3)]),('gem',[(2,7)]),('geode',[(5,6)]),
  ('statue',[(5,1)]),('statue',[(7,0)]),('tree',[(6,2)]),('table',[(7,5)]),('chair',[(6,4)]),('chair',[(7,4)]),('bench',[(3,6),(3,7)])],
 names=['Ada','Barnaby','Cecily','Dashiell','Eloise','Fergus','Ginevra','Horace']),
dict(id='c8',num='08',title='Carnival of Lanterns',difficulty='Hard',
 rooms=["TTTFFFF","TTTFFFF","MMCCCWW","MMCCCWW","MMCCCWW","GGGSSSW","GGGSSSS"],
 roomNames=dict(T='Big top',F='Ferris wheel',M='Mirror maze',C='Carousel',W='Food stalls',G='Games alley',S='Duck pond'),
 floors=dict(T='sand',F='pavement',M='metal',C='wood',W='grass',G='sand',S='water'),
 objects=[('tent',[(0,1)]),('ferris',[(0,4),(0,5),(1,4),(1,5)]),('mirror',[(2,0)]),('mirror',[(4,1)]),
  ('horse',[(2,2)]),('horse',[(2,4)]),('horse',[(4,2)]),('horse',[(4,4)]),('pole',[(3,3)]),('candy',[(3,6)]),('bench',[(4,5),(5,6)]) ,
  ('target',[(5,0)]),('duck',[(6,4)]),('duck',[(5,4)]),('bench',[(1,0),(1,1)])],
 names=['Anouk','Bram','Coco','Dex','Etta','Flint','Gus']),
dict(id='c9',num='09',title='Hotel Grand Meridian',difficulty='Hard',
 rooms=["LLLLBBBBPPPP","LLLLBBBBPPPP","LLRRRBBSSPPP","KKRRRGGSSSTT","KKRRGGGGSSTT","KKKCGGGGWWTT",
        "DDCCCGGWWWTT","DDCCCHHWWOOO","DDDHHHHHOOOO","YYDHHHHEEEOO","YYYYZZEEEEMM","YYYYZZZEEMMM"],
 roomNames=dict(L='Lobby',B='Ballroom',P='Penthouse',R='Bar',S='Suite',K='Kitchen',G='Atrium',T='Terrace',C='Cloakroom',
  W='Wine cellar',D='Dining room',H='Hallway',O='Office',Y='Pool',Z='Laundry',E='Library',M='Boiler room'),
 floors=dict(L='marble',B='wood',P='carpet',R='wood',S='carpet',K='tile',G='grass',T='pavement',C='carpet',W='stone',D='wood',
  H='marble',O='wood',Y='water',Z='tile',E='wood',M='metal'),
 objects=[('desk',[(0,1),(0,2)]),('plant',[(1,3)]),('sofa',[(1,0),(1,1)]),('piano',[(0,5)]),('carpet',[(1,5),(1,6)]),('chair',[(2,6)]),
  ('bed',[(0,9),(0,10)]),('TV',[(1,11)]),('chair',[(2,10)]),('table',[(3,3)]),('chair',[(2,2)]),('chair',[(4,3)]),
  ('bed',[(2,7),(3,7)]),('shelf',[(4,9)]),('stove',[(3,0)]),('table',[(4,1)]),('fountain',[(4,6)]),('tree',[(5,5)]),('bench',[(6,5),(6,6)]),
  ('tree',[(3,11)]),('lounger',[(5,10)]),('lounger',[(6,11)]),('crate',[(6,2)]),('barrel',[(6,9)]),('barrel',[(7,8)]),
  ('table',[(7,0)]),('chair',[(6,0)]),('chair',[(8,1)]),('cart',[(8,5)]),('carpet',[(7,5),(7,6)]),('desk',[(8,10),(8,11)]),('chair',[(7,10)]),
  ('float',[(10,1)]),('lounger',[(9,0)]),('washer',[(10,4)]),('shelf',[(9,8)]),('sofa',[(10,6),(10,7)]),('boiler',[(11,11)]),('crate',[(10,10)]),('lift',[(11,4)])],
 names=['Aurelia','Benedict','Camille','Desmond','Evangeline','Florian','Genevieve','Hector','Imogen','Jasper','Katarina','Leopold']),
]
